### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'write'

### ISSUE THREAD

**Issue by haoziyeung** [bioinform/varsim#144]
Hi,there,i'm using varsim to create a simulated somatic data,and i hava a error message,like below:
`python varsim_somatic.py --reference /gpfs/users/yanghao/database/ref/b37/human_g1k_v37_decoy.fasta --id cosmic --som_num_snp 10000 --som_num_ins 2000 --som_num_del 2000 --som_num_mnp 200 --som_num_complex 200 --cosmic_vcf cosmic.vcf.gz --normal_vcf somatic_sim_data/simu.truth.vcf --nlanes 1 --total_coverage 2000 --simulator art --simulator_executable ART/art_bin_MountRainier/art_illumina --out_dir som_out --log_dir som_log --work_dir som_work --sv_insert_seq insert_seq.txt`
`Traceback (most recent call last):
  File "varsim_somatic.py", line 227, in <module>
    varsim_somatic_main()
  File "varsim_somatic.py", line 202, in varsim_somatic_main
    processes = monitor_processes(processes)
  File "/gpfs/users/yanghao/software/varsim_run/varsim.py", line 140, in monitor_processes
    logger.write("Could not kill the process " + str(p.pid))
AttributeError: 'Logger' object has no attribute 'write'
`
can anybody tell  me how to fix it? thanks a lot!

**Comment by yunfeiguo** [comment]
Hi @haoziyeung 

Please pull from `master` branch and try again. Thanks!
