### ISSUE TITLE
Exception: Aborting... Please check log for details.

### ISSUE THREAD

**Issue by haoziyeung** [bioinform/varsim#148]
Hello ,sorry for bother your again,i'm using varsim_multi.py to get simulated data,here is my command:

`python /gpfs/users/yanghao/software/varsim/varsim_multi.py --regions ../Euler_MSKCC_actionable_cancer_original.sort.bed --sv_insert_seq /gpfs/users/yanghao/software/varsim_run/insert_seq.txt --sv_dgv /gpfs/users/yanghao/software/varsim_run/GRCh37_hg19_supportingvariants_2013-07-23.txt --reference /gpfs/users/yanghao/database/ref/b37/human_g1k_v37_decoy.fasta --vc_num_snp 3000000 --vc_num_ins 100000 --vc_num_del 100000 --vc_num_mnp 0 --vc_num_complex 0 --sv_num_ins 0 --sv_num_del 0 --sv_num_dup 0 --sv_num_inv 0 --sv_percent_novel 0 --vc_percent_novel 0 --vc_min_length_lim 0 --vc_max_length_lim 49 --sv_min_length_lim 50 --sv_max_length_lim 1000000 --nlanes 10 --total_coverage 10 --simulator_executable /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina --out_dir . --simulator art --log_to_stderr --loglevel debug --sampling_vcf /gpfs/users/yanghao/database/ncbi/dbsnp/All_20170710.vcf.gz --samples region-specific-simulation --samples_random 1`

and i get ERROR:

`INFO 2018-02-08 16:18:33,278 concatenate_files    Removing ./region-specific-simulation/out/X_123224425_123224614_region-specific-simulation.vcf
INFO 2018-02-08 16:18:33,279 concatenate_files    Removing ./region-specific-simulation/out/X_123224704_123224814_region-specific-simulation.vcf
INFO 2018-02-08 16:18:33,281 concatenate_files    Removing ./region-specific-simulation/out/X_123227868_123227994_region-specific-simulation.vcf
INFO 2018-02-08 16:18:33,284 concatenate_files    Removing ./region-specific-simulation/out/X_123229222_123229299_region-specific-simulation.vcf
INFO 2018-02-08 16:18:33,286 concatenate_files    Removing ./region-specific-simulation/out/X_123234424_123234447_region-specific-simulation.vcf
INFO 2018-02-08 16:18:33,288 concatenate_files    Removing ./region-specific-simulation/out/X_123480493_123480629_region-specific-simulation.vcf
INFO 2018-02-08 16:18:33,290 concatenate_files    Removing ./region-specific-simulation/out/X_123499611_123499674_region-specific-simulation.vcf
INFO 2018-02-08 16:18:33,291 concatenate_files    Removing ./region-specific-simulation/out/X_123504026_123504170_region-specific-simulation.vcf
INFO 2018-02-08 16:18:33,293 concatenate_files    Removing ./region-specific-simulation/out/X_123505201_123505241_region-specific-simulation.vcf
INFO 2018-02-08 16:18:33,295 run_vcfstats         Executing command java -Xmx1g -Xms1g -jar /gpfs/users/yanghao/software/varsim_run/VarSim.jar vcfstats -vcf ./region-specific-simulation/out/region-specific-simulation.truth.vcf
INFO 2018-02-08 16:18:33,360 run_vcfstats          with pid 108965
INFO 2018-02-08 16:18:36,363 monitor_processes    Process 108965 exited with code 0
INFO 2018-02-08 16:18:36,367 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane0.read1.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane0.read1.fq.gz
INFO 2018-02-08 16:18:36,388 varsim_main           with pid 108987
INFO 2018-02-08 16:18:36,389 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane0.read1.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane0.read1.aln.gz
INFO 2018-02-08 16:18:36,410 varsim_main           with pid 108990
INFO 2018-02-08 16:18:36,411 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane0.read2.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane0.read2.fq.gz
INFO 2018-02-08 16:18:36,432 varsim_main           with pid 108993
INFO 2018-02-08 16:18:36,432 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane0.read2.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane0.read2.aln.gz
INFO 2018-02-08 16:18:36,450 varsim_main           with pid 108996
INFO 2018-02-08 16:18:36,451 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane1.read1.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane1.read1.fq.gz
INFO 2018-02-08 16:18:36,468 varsim_main           with pid 108999
INFO 2018-02-08 16:18:36,469 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane1.read1.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane1.read1.aln.gz
INFO 2018-02-08 16:18:36,485 varsim_main           with pid 109002
INFO 2018-02-08 16:18:36,486 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane1.read2.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane1.read2.fq.gz
INFO 2018-02-08 16:18:36,505 varsim_main           with pid 109005
INFO 2018-02-08 16:18:36,505 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane1.read2.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane1.read2.aln.gz
INFO 2018-02-08 16:18:36,523 varsim_main           with pid 109008
INFO 2018-02-08 16:18:36,524 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane2.read1.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane2.read1.fq.gz
INFO 2018-02-08 16:18:36,541 varsim_main           with pid 109011
INFO 2018-02-08 16:18:36,541 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane2.read1.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane2.read1.aln.gz
INFO 2018-02-08 16:18:36,557 varsim_main           with pid 109014
INFO 2018-02-08 16:18:36,558 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane2.read2.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane2.read2.fq.gz
INFO 2018-02-08 16:18:36,573 varsim_main           with pid 109017
INFO 2018-02-08 16:18:36,574 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane2.read2.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane2.read2.aln.gz
INFO 2018-02-08 16:18:36,589 varsim_main           with pid 109020
INFO 2018-02-08 16:18:36,590 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane3.read1.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane3.read1.fq.gz
INFO 2018-02-08 16:18:36,605 varsim_main           with pid 109023
INFO 2018-02-08 16:18:36,606 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane3.read1.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane3.read1.aln.gz
INFO 2018-02-08 16:18:36,621 varsim_main           with pid 109026
INFO 2018-02-08 16:18:36,622 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane3.read2.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane3.read2.fq.gz
INFO 2018-02-08 16:18:36,642 varsim_main           with pid 109029
INFO 2018-02-08 16:18:36,643 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane3.read2.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane3.read2.aln.gz
INFO 2018-02-08 16:18:36,661 varsim_main           with pid 109032
INFO 2018-02-08 16:18:36,662 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane4.read1.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane4.read1.fq.gz
INFO 2018-02-08 16:18:36,680 varsim_main           with pid 109035
INFO 2018-02-08 16:18:36,680 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane4.read1.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane4.read1.aln.gz
INFO 2018-02-08 16:18:36,697 varsim_main           with pid 109038
INFO 2018-02-08 16:18:36,698 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane4.read2.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane4.read2.fq.gz
INFO 2018-02-08 16:18:36,713 varsim_main           with pid 109041
INFO 2018-02-08 16:18:36,714 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane4.read2.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane4.read2.aln.gz
INFO 2018-02-08 16:18:36,729 varsim_main           with pid 109044
INFO 2018-02-08 16:18:36,730 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane5.read1.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane5.read1.fq.gz
INFO 2018-02-08 16:18:36,745 varsim_main           with pid 109047
INFO 2018-02-08 16:18:36,745 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane5.read1.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane5.read1.aln.gz
INFO 2018-02-08 16:18:36,760 varsim_main           with pid 109050
INFO 2018-02-08 16:18:36,760 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane5.read2.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane5.read2.fq.gz
INFO 2018-02-08 16:18:36,775 varsim_main           with pid 109053
INFO 2018-02-08 16:18:36,776 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane5.read2.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane5.read2.aln.gz
INFO 2018-02-08 16:18:36,789 varsim_main           with pid 109056
INFO 2018-02-08 16:18:36,790 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane6.read1.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane6.read1.fq.gz
INFO 2018-02-08 16:18:36,803 varsim_main           with pid 109059
INFO 2018-02-08 16:18:36,803 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane6.read1.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane6.read1.aln.gz
INFO 2018-02-08 16:18:36,816 varsim_main           with pid 109062
INFO 2018-02-08 16:18:36,817 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane6.read2.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane6.read2.fq.gz
INFO 2018-02-08 16:18:36,829 varsim_main           with pid 109065
INFO 2018-02-08 16:18:36,830 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane6.read2.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane6.read2.aln.gz
INFO 2018-02-08 16:18:36,842 varsim_main           with pid 109068
INFO 2018-02-08 16:18:36,843 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane7.read1.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane7.read1.fq.gz
INFO 2018-02-08 16:18:36,855 varsim_main           with pid 109071
INFO 2018-02-08 16:18:36,855 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane7.read1.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane7.read1.aln.gz
INFO 2018-02-08 16:18:36,867 varsim_main           with pid 109074
INFO 2018-02-08 16:18:36,868 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane7.read2.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane7.read2.fq.gz
INFO 2018-02-08 16:18:36,879 varsim_main           with pid 109077
INFO 2018-02-08 16:18:36,880 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane7.read2.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane7.read2.aln.gz
INFO 2018-02-08 16:18:36,891 varsim_main           with pid 109080
INFO 2018-02-08 16:18:36,891 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane8.read1.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane8.read1.fq.gz
INFO 2018-02-08 16:18:36,902 varsim_main           with pid 109083
INFO 2018-02-08 16:18:36,903 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane8.read1.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane8.read1.aln.gz
INFO 2018-02-08 16:18:36,914 varsim_main           with pid 109086
INFO 2018-02-08 16:18:36,914 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane8.read2.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane8.read2.fq.gz
INFO 2018-02-08 16:18:36,925 varsim_main           with pid 109089
INFO 2018-02-08 16:18:36,926 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane8.read2.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane8.read2.aln.gz
INFO 2018-02-08 16:18:36,936 varsim_main           with pid 109092
INFO 2018-02-08 16:18:36,937 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane9.read1.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane9.read1.fq.gz
INFO 2018-02-08 16:18:36,947 varsim_main           with pid 109095
INFO 2018-02-08 16:18:36,947 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane9.read1.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane9.read1.aln.gz
INFO 2018-02-08 16:18:36,958 varsim_main           with pid 109098
INFO 2018-02-08 16:18:36,958 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane9.read2.fq | gzip -2 > ./region-specific-simulation/out/simulated.lane9.read2.fq.gz
INFO 2018-02-08 16:18:36,968 varsim_main           with pid 109101
INFO 2018-02-08 16:18:36,969 varsim_main          Executing command cat ./region-specific-simulation/out/simulated.lane9.read2.aln | gzip -2 > ./region-specific-simulation/out/simulated.lane9.read2.aln.gz
INFO 2018-02-08 16:18:36,979 varsim_main           with pid 109104
INFO 2018-02-08 16:18:36,990 varsim_main          Executing command /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina  -i ./region-specific-simulation/out/region-specific-simulation.fa -f 0.5 -rs 0 -o ./region-specific-simulation/out/simulated.lane0.read with pid 109107
INFO 2018-02-08 16:18:37,000 varsim_main          Executing command /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina  -i ./region-specific-simulation/out/region-specific-simulation.fa -f 0.5 -rs 1 -o ./region-specific-simulation/out/simulated.lane1.read with pid 109108
INFO 2018-02-08 16:18:37,011 varsim_main          Executing command /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina  -i ./region-specific-simulation/out/region-specific-simulation.fa -f 0.5 -rs 2 -o ./region-specific-simulation/out/simulated.lane2.read with pid 109109
INFO 2018-02-08 16:18:37,026 varsim_main          Executing command /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina  -i ./region-specific-simulation/out/region-specific-simulation.fa -f 0.5 -rs 3 -o ./region-specific-simulation/out/simulated.lane3.read with pid 109110
INFO 2018-02-08 16:18:37,039 varsim_main          Executing command /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina  -i ./region-specific-simulation/out/region-specific-simulation.fa -f 0.5 -rs 4 -o ./region-specific-simulation/out/simulated.lane4.read with pid 109111
INFO 2018-02-08 16:18:37,052 varsim_main          Executing command /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina  -i ./region-specific-simulation/out/region-specific-simulation.fa -f 0.5 -rs 5 -o ./region-specific-simulation/out/simulated.lane5.read with pid 109112
INFO 2018-02-08 16:18:37,065 varsim_main          Executing command /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina  -i ./region-specific-simulation/out/region-specific-simulation.fa -f 0.5 -rs 6 -o ./region-specific-simulation/out/simulated.lane6.read with pid 109113
INFO 2018-02-08 16:18:37,078 varsim_main          Executing command /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina  -i ./region-specific-simulation/out/region-specific-simulation.fa -f 0.5 -rs 7 -o ./region-specific-simulation/out/simulated.lane7.read with pid 109114
INFO 2018-02-08 16:18:37,091 varsim_main          Executing command /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina  -i ./region-specific-simulation/out/region-specific-simulation.fa -f 0.5 -rs 8 -o ./region-specific-simulation/out/simulated.lane8.read with pid 109115
INFO 2018-02-08 16:18:37,103 varsim_main          Executing command /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina  -i ./region-specific-simulation/out/region-specific-simulation.fa -f 0.5 -rs 9 -o ./region-specific-simulation/out/simulated.lane9.read with pid 109116
INFO 2018-02-08 16:18:38,107 monitor_processes    Process 109107 exited with code 1
ERROR 2018-02-08 16:18:38,107 monitor_processes    Process 109107 failed. Will kill the remaining processes.
INFO 2018-02-08 16:18:38,107 monitor_processes    Process 109108 exited with code 1
ERROR 2018-02-08 16:18:38,107 monitor_processes    Process 109108 failed. Will kill the remaining processes.
INFO 2018-02-08 16:18:38,107 monitor_processes    Process 109109 exited with code 1
ERROR 2018-02-08 16:18:38,108 monitor_processes    Process 109109 failed. Will kill the remaining processes.
INFO 2018-02-08 16:18:38,108 monitor_processes    Process 109110 exited with code 1
ERROR 2018-02-08 16:18:38,108 monitor_processes    Process 109110 failed. Will kill the remaining processes.
INFO 2018-02-08 16:18:38,108 monitor_processes    Process 109111 exited with code 1
ERROR 2018-02-08 16:18:38,108 monitor_processes    Process 109111 failed. Will kill the remaining processes.
INFO 2018-02-08 16:18:38,108 monitor_processes    Process 109112 exited with code 1
ERROR 2018-02-08 16:18:38,108 monitor_processes    Process 109112 failed. Will kill the remaining processes.
INFO 2018-02-08 16:18:38,108 monitor_processes    Process 109113 exited with code 1
ERROR 2018-02-08 16:18:38,108 monitor_processes    Process 109113 failed. Will kill the remaining processes.
INFO 2018-02-08 16:18:38,109 monitor_processes    Process 109114 exited with code 1
ERROR 2018-02-08 16:18:38,109 monitor_processes    Process 109114 failed. Will kill the remaining processes.
INFO 2018-02-08 16:18:38,109 monitor_processes    Process 109115 exited with code 1
ERROR 2018-02-08 16:18:38,109 monitor_processes    Process 109115 failed. Will kill the remaining processes.
INFO 2018-02-08 16:18:38,109 monitor_processes    Process 109116 exited with code 1
ERROR 2018-02-08 16:18:38,109 monitor_processes    Process 109116 failed. Will kill the remaining processes.
ERROR 2018-02-08 16:18:38,109 monitor_processes    Could not kill the process 108987
ERROR 2018-02-08 16:18:38,109 monitor_processes    Could not kill the process 108990
ERROR 2018-02-08 16:18:38,110 monitor_processes    Could not kill the process 108993
ERROR 2018-02-08 16:18:38,110 monitor_processes    Could not kill the process 108996
ERROR 2018-02-08 16:18:38,110 monitor_processes    Could not kill the process 108999
ERROR 2018-02-08 16:18:38,110 monitor_processes    Could not kill the process 109002
ERROR 2018-02-08 16:18:38,110 monitor_processes    Could not kill the process 109005
ERROR 2018-02-08 16:18:38,110 monitor_processes    Could not kill the process 109008
ERROR 2018-02-08 16:18:38,110 monitor_processes    Could not kill the process 109011
ERROR 2018-02-08 16:18:38,110 monitor_processes    Could not kill the process 109014
ERROR 2018-02-08 16:18:38,110 monitor_processes    Could not kill the process 109017
ERROR 2018-02-08 16:18:38,111 monitor_processes    Could not kill the process 109020
ERROR 2018-02-08 16:18:38,111 monitor_processes    Could not kill the process 109023
ERROR 2018-02-08 16:18:38,111 monitor_processes    Could not kill the process 109026
ERROR 2018-02-08 16:18:38,111 monitor_processes    Could not kill the process 109029
ERROR 2018-02-08 16:18:38,111 monitor_processes    Could not kill the process 109032
ERROR 2018-02-08 16:18:38,111 monitor_processes    Could not kill the process 109035
ERROR 2018-02-08 16:18:38,111 monitor_processes    Could not kill the process 109038
ERROR 2018-02-08 16:18:38,111 monitor_processes    Could not kill the process 109041
ERROR 2018-02-08 16:18:38,111 monitor_processes    Could not kill the process 109044
ERROR 2018-02-08 16:18:38,112 monitor_processes    Could not kill the process 109047
ERROR 2018-02-08 16:18:38,112 monitor_processes    Could not kill the process 109050
ERROR 2018-02-08 16:18:38,112 monitor_processes    Could not kill the process 109053
ERROR 2018-02-08 16:18:38,112 monitor_processes    Could not kill the process 109056
ERROR 2018-02-08 16:18:38,112 monitor_processes    Could not kill the process 109059
ERROR 2018-02-08 16:18:38,112 monitor_processes    Could not kill the process 109062
ERROR 2018-02-08 16:18:38,112 monitor_processes    Could not kill the process 109065
ERROR 2018-02-08 16:18:38,112 monitor_processes    Could not kill the process 109068
ERROR 2018-02-08 16:18:38,112 monitor_processes    Could not kill the process 109071
ERROR 2018-02-08 16:18:38,113 monitor_processes    Could not kill the process 109074
ERROR 2018-02-08 16:18:38,113 monitor_processes    Could not kill the process 109077
ERROR 2018-02-08 16:18:38,113 monitor_processes    Could not kill the process 109080
ERROR 2018-02-08 16:18:38,113 monitor_processes    Could not kill the process 109083
ERROR 2018-02-08 16:18:38,113 monitor_processes    Could not kill the process 109086
ERROR 2018-02-08 16:18:38,113 monitor_processes    Could not kill the process 109089
ERROR 2018-02-08 16:18:38,113 monitor_processes    Could not kill the process 109092
ERROR 2018-02-08 16:18:38,113 monitor_processes    Could not kill the process 109095
ERROR 2018-02-08 16:18:38,113 monitor_processes    Could not kill the process 109098
ERROR 2018-02-08 16:18:38,113 monitor_processes    Could not kill the process 109101
ERROR 2018-02-08 16:18:38,114 monitor_processes    Could not kill the process 109104
Traceback (most recent call last):
  File "/gpfs/users/yanghao/software/varsim/varsim_multi.py", line 256, in <module>
    samples_random=args.samples_random)
  File "/gpfs/users/yanghao/software/varsim/varsim_multi.py", line 111, in varsim_multi
    disable_vcf2diploid)
  File "/gpfs/users/yanghao/software/varsim/varsim.py", line 472, in varsim_main
    monitor_processes(processes)
  File "/gpfs/users/yanghao/software/varsim/varsim.py", line 141, in monitor_processes
    raise Exception('Aborting... Please check log for details.')
Exception: Aborting... Please check log for details.
`
**i don't know what happend?
and i'm wondering,this command is for germline data within certain interval
but how can i get tumor data in a certain interval too?**

Thanks a lot.

**Comment by haoziyeung** [comment]
@marghoob

**Comment by marghoob** [comment]
@haoziyeung Could you please attach your log directory as a tar-gzipped archive and we will have a look. It looks like one of the processes failed for some reason and we are hoping the log files would have information about it.

**Comment by zhuang96** [comment]
Hello @marghoob , I am having the same issue as well (pulled the new master because I was having the Logger attribute 'write' problem and now "Exception (Aborting...")). 

Attached is my log achieve. Thank you!  
[varsim_log.tar.gz](https://github.com/bioinform/varsim/files/1708535/varsim_log.tar.gz)

**Comment by yunfeiguo** [comment]
@zhuang96 apparently the command is different from the 1st user, could you post it here?

**Comment by zhuang96** [comment]
Hello @yunfeiguo , this is my command input for testing

`./varsim-master/varsim.py --vc_in_vcf All.20170710.vcf.gz --sv_insert_seq insert_seq.txt \
--sv_dgv GRCh38_hg38_supportingvariants_2016-08-31.txt\
--reference /project/vntrseek/share/GRCh38/GRCh38.fa --id simu --read_length 100 --vc_num_snp 3000000 --vc_num_ins 100000 \
--vc_num_del 100000 --vc_num_mnp 50000 --vc_num_complex 50000 --sv_num_ins 2000 \
--sv_num_del 2000 --sv_num_dup 200 --sv_num_inv 1000 --sv_percent_novel 0.01 \
--vc_percent_novel 0.01 --mean_fragment_size 350 --sd_fragment_size 50 \
--vc_min_length_lim 0 --vc_max_length_lim 49 --sv_min_length_lim 50 \
--sv_max_length_lim 1000000 --nlanes 5 --total_coverage 1 \
--simulator_executable ART/art_bin_VanillaIceCream/art_illumina --out_dir out --log_dir log --work_dir work \
--simulator art  \`

Thank you.

**Comment by yunfeiguo** [comment]
Thanks, @zhuang96 @haoziyeung 

We are working on this issue.

**Comment by haoziyeung** [comment]
Hello, @yunfeiguo ,here is my cmd:
`python /gpfs/users/yanghao/software/varsim/varsim_multi.py --regions ../Euler_MSKCC_actionable_cancer_original.sort.bed --sv_insert_seq /gpfs/users/yanghao/software/varsim_run/insert_seq.txt --sv_dgv /gpfs/users/yanghao/software/varsim_run/GRCh37_hg19_supportingvariants_2013-07-23.txt --reference /gpfs/users/yanghao/database/ref/b37/human_g1k_v37_decoy.fasta --vc_num_snp 3000000 --vc_num_ins 100000 --vc_num_del 100000 --vc_num_mnp 0 --vc_num_complex 0 --sv_num_ins 0 --sv_num_del 0 --sv_num_dup 0 --sv_num_inv 0 --sv_percent_novel 0 --vc_percent_novel 0 --vc_min_length_lim 0 --vc_max_length_lim 49 --sv_min_length_lim 50 --sv_max_length_lim 1000000 --nlanes 10 --total_coverage 10 --simulator_executable /gpfs/users/yanghao/software/varsim_run/ART/art_bin_MountRainier/art_illumina --out_dir . --simulator art --loglevel debug --sampling_vcf /gpfs/users/yanghao/database/ncbi/dbsnp/All_20170710.vcf.gz --samples region-specific-simulation --samples_random 1`

`Traceback (most recent call last):
  File "/gpfs/users/yanghao/software/varsim/varsim_multi.py", line 256, in <module>
    samples_random=args.samples_random)
  File "/gpfs/users/yanghao/software/varsim/varsim_multi.py", line 111, in varsim_multi
    disable_vcf2diploid)
  File "/gpfs/users/yanghao/software/varsim/varsim.py", line 472, in varsim_main
    monitor_processes(processes)
  File "/gpfs/users/yanghao/software/varsim/varsim.py", line 141, in monitor_processes
    raise Exception('Aborting... Please check log for details.')
Exception: Aborting... Please check log for details.
`

Attached is my log achieve. Thank you!
[varsim.log.tar.gz](https://github.com/bioinform/varsim/files/1746771/varsim.log.tar.gz)

**Comment by yunfeiguo** [comment]
@haoziyeung thanks, I suspect this is still caused by attempt to restrict dgv in some region (which is not supported yet). We will work on this (and maybe additional information is needed later). Thanks.
