### ISSUE TITLE
Error in RandDGVtoVCF of varsim_multi

### ISSUE THREAD

**Issue by thomas-davis** [bioinform/varsim#191]
Hi, I'm trying to run Varsim_multi.py on hg19, using a BED file of exonic regions I downloaded from ucsc table browser. I'm using
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
and python 2.7.15. 
the BED files appears normal to me. 
chr1    11673   12427   uc001aaa.3_exon_0_200_chr1_11874_f      0       +
chr1    12412   12921   uc001aaa.3_exon_1_200_chr1_12613_f      0       +
chr1    13020   14609   uc001aaa.3_exon_2_200_chr1_13221_f      0       +
chr1    11673   12427   uc010nxr.1_exon_0_200_chr1_11874_f      0       +
etc. 

I'm getting the following error in dgv2vcf.err
13 Mar 2019 14:08:32,149 ERROR [main] (SimpleReference.java:157): byteRange: Invalid range
Exception in thread "main" java.lang.NullPointerException
        at java.lang.String.<init>(String.java:491)
        at com.bina.varsim.types.variant.Variant.setNovelPosition(Variant.java:328)
        at com.bina.varsim.tools.simulation.RandDGV2VCF.randOutputVcfRecord(RandDGV2VCF.java:248)
        at com.bina.varsim.tools.simulation.RandDGV2VCF.sampleFromDGV(RandDGV2VCF.java:217)
        at com.bina.varsim.tools.simulation.RandDGV2VCF.run(RandDGV2VCF.java:298)
        at com.bina.varsim.VarSim.runVarSimTool(VarSim.java:68)
        at com.bina.varsim.VarSim.run(VarSim.java:121)
        at com.bina.varsim.VarSim.main(VarSim.java:32)

I think generating the restricted ref worked-- the restricted directory has two files ref.fa and its index. 
Let me know if you need anything other information. 
Thank you very much!

**Comment by yunfeiguo** [comment]
Hi @thomas-davis what was the command used? And could you provide the input file to RandDGV2VCF as well (just enough for us to reproduce the error)?

**Comment by thomas-davis** [comment]
Thanks very much for the quick response. This is the command I'm using: 

./varsim_multi.py --samples_random 1 --sampling_vcf All.vcf.gz --total_coverage 15 --sv_insert_seq insert_seq.txt --simulator_options "-p -l 100 -m 350 -s 50" --sv_dgv GRCh37_hg19_supportingvariants_2013-07-23.txt --vc_num_snp 300 --vc_num_ins 100 --vc_num_del 100 --vc_num_mnp 50 --vc_num_complex 50 --sv_num_ins 50 --sv_num_del 50 --sv_num_dup 50 --sv_num_inv 50 --sv_percent_novel 0.01 --vc_percent_novel 0.01 --vc_min_length_lim 0 --vc_max_length_lim 49 --sv_min_length_lim 50 --sv_max_length_lim 1000000 --java_max_mem 40g --simulator_executable ART/art_bin_VanillaIceCream/art_illumina --out_dir 3_18_WES --simulator art --loglevel debug --regions exome_bed.bed --reference hg19.fa

The DGV file I'm using I downloaded from http://web.stanford.edu/group/wonglab/varsim/GRCh37_hg19_supportingvariants_2013-07-23.txt, as shown in varsims website. I can try making a smaller example that reproduces the error if you don't want to have to use the whole dgv. 

Interestingly, RandDGV2VCF actually outputs a file called dgv.vcf in the tmp directory. I'll attach a .txt version, and a screenshot of what it looks like. The alt column always begins with "^@"
<img width="576" alt="varsim_dgv" src="https://user-images.githubusercontent.com/33948820/54550950-61b05400-4983-11e9-972e-33d913660a0e.png">

[dgv.txt](https://github.com/bioinform/varsim/files/2979504/dgv.txt)

**Comment by yunfeiguo** [comment]
Thanks, @thomas-davis, we'll look into this.

**Comment by thomas-davis** [comment]
Hello, 
If you don't mind, I was wondering what you thought of this workaround to use in the meantime. I was going to supply varsim.py a vcf and dgv file with errors only in exonic regions, and use the --disable_sim flag. Then I was going to run Wessim on the simulated genome output by varsim, to hopefully get realistic variant containing WES. Do you think this is a reasonable approach? 

Thanks!

**Comment by yunfeiguo** [comment]
Hi @thomas-davis if varsim works with dgv without any error, then this should work. Read simulation should be fine anyway. Alternatively you can supply a VCF containing structural variants (SV) in place of a dgv file to completely bypass `RandDGV2VCF`.

**Comment by yunfeiguo** [comment]
Hi @thomas-davis actually I noticed that the reference genome does not match the database (dgv doesn't have `chr` prefix for chromosome names but hg19 has it). Could you please try again with a different reference genome, say ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz

**Comment by thomas-davis** [comment]
Thanks very much, I'll try again with that reference. Do you know where I might be able to find a bed file of exonic regions for that sequence? Do you think the BED file of exonic regions from USCS table browser for hg19 would work? 
Thanks again.

**Comment by yunfeiguo** [comment]
if you only care about primary autosomal chromosomes (e.g. chr1, chr2, ..., chr22) plus chrX, you can use the exome BED based on hg19, but the `chr` prefix needs to be removed. Otherwise, you'll need to find a BED file that corresponds to the reference file being used.
