### ISSUE TITLE
Varsim error: returned non-zero exit status 1

### ISSUE THREAD

**Issue by bioinfo89** [bioinform/varsim#239]
Hi,

I am using chr21 for simulation of variants. The following the command I am using to do so:

python /WGS_tools/varsim/varsim.py --vc_in_vcf /WGS_tools/varsim/All_20170710.vcf --sv_insert_seq /WGS_tools/varsim/insert_seq.txt --sv_dgv /WGS_tools/DGV/GRCh37_hg19_variants_2020-02-25.txt --reference /WGS_SV_analysis/hg19/chr21.fa --id Simchr21 --read_length 125 --mean_fragment_size 500 --sd_fragment_size 100 --vc_num_snp 100 --vc_num_ins 50 --vc_num_del 500 --sv_num_ins 3000 --sv_num_del 5000 --sv_num_dup 2000 --sv_num_inv 500 --sv_percent_novel 0.2 --vc_percent_novel 0.01 --vc_min_length_lim 0  --vc_max_length_lim 29  --sv_min_length_lim 30 --sv_max_length_lim 1000000 --nlanes 1 --total_coverage 30 --simulator_executable /WGS_tools/art_bin_MountRainier/art_illumina --out_dir /WGS_SV_analysis/Varsim_trial/ --log_dir log --simulator art --profile_1 /WGS_tools/art_bin_MountRainier/Illumina_profiles/HiSeq2500L125R1.txt --profile_2 /WGS_tools/art_bin_MountRainier/Illumina_profiles/HiSeq2500L125R2.txt --varsim_jar /WGS_tools/varsim/VarSim.jar

The program runs for 4 hours and terminates with the following error:

Traceback (most recent call last):
  File "/WGS_tools/varsim/varsim.py", line 719, in <module>
    java=args.java)
  File "/WGS_tools/varsim/varsim.py", line 333, in varsim_main
    run_randvcf(os.path.realpath(sampling_vcf), rand_vcf_out_fd, rand_vcf_log_fd, seed, sex, randvcf_options, reference, java)
  File "/WGS_tools/varsim/varsim.py", line 242, in run_randvcf
    subprocess.check_call(rand_vcf_command, stdout=out_vcf_fd, stderr=log_file_fd)
  File "/opt/ohpc/pub/packages/anaconda2/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/WGS_tools/varsim/opt/jdk1.8.0_131/bin/java', '-Xmx10g', '-jar', '/WGS_tools/varsim/VarSim.jar', 'randvcf2vcf', '-seed', '0', '-t', 'MALE', '-num_snp', '100', '-num_ins', '50', '-num_del', '500', '-num_mnp', '0', '-num_complex', '0', '-num_dup', '0', '-num_inv', '0', '-novel', '0.01', '-min_len', '0', '-max_len', '29', '-prop_het', '0.6', '-ref', '/WGS_SV_analysis/hg19/chr21.fa', '-vcf', '/WGS_tools/varsim/All_20170710.vcf']' returned non-zero exit status 1

Any help to resolve this issue would be great! Thanks!

**Comment by yunfeiguo** [comment]
Hi @bioinfo89 could you attach the log files (they are in `log/` folder)? Thanks.

**Comment by bioinfo89** [comment]
Hi Guo,

Please find attached the log files.
Best,
Khyati Chandratre

**Comment by bioinfo89** [comment]
[varsim.log](https://github.com/bioinform/varsim/files/5171038/varsim.log)

**Comment by yunfeiguo** [comment]
If you just run `/scratch/krc190002/WGS_tools/varsim/opt/jdk1.8.0_131/bin/java -Xmx10g -jar /scratch/krc190002/WGS_tools/varsim/VarSim.jar randvcf2vcf -seed 0 -t MALE -num_snp 100 -num_ins 50 -num_del 500 -num_mnp 0 -num_complex 0 -num_dup 0 -num_inv 0 -novel 0.01 -min_len 0 -max_len 29 -prop_het 0.6 -ref /scratch/krc190002/WGS_SV_analysis/hg19/chr21.fa -vcf /scratch/krc190002/WGS_tools/varsim/All_20170710.vcf` what message/error would you see?

**Comment by bioinfo89** [comment]
Please find attached the error file after I ran the mentioned command.
Best,
Khyati Chandratre

**Comment by bioinfo89** [comment]
Following is the error message:

```
0;SAO=0;VP=0x050060080005000002100200;GENEINFO=CDKN1C:1028;WGT=1;VC=DIV;PM;INT;ASP;LSD
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3210)
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:261)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
        at java.util.ArrayList.add(ArrayList.java:458)
        at com.bina.varsim.tools.simulation.RandVCF2VCF.countVariants(RandVCF2VCF.java:118)
        at com.bina.varsim.tools.simulation.RandVCF2VCF.run(RandVCF2VCF.java:291)
        at com.bina.varsim.VarSim.runVarSimTool(VarSim.java:65)
        at com.bina.varsim.VarSim.run(VarSim.java:121)
        at com.bina.varsim.VarSim.main(VarSim.java:32)

real    276m12.765s
user    3067m57.323s
sys     16m15.140s
```

**Comment by yunfeiguo** [comment]
Hi @bioinfo89 the error message suggests that more memory is needed for Java. For `varsim.py`, you can set `--java_max_mem` option to a larger value, e.g. `20g`. The default is `10g`. You need to experiment a bit to see how much memory is sufficient. In addition, if you are only interested in `chr21`, you can subsample `/scratch/krc190002/WGS_tools/varsim/All_20170710.vcf` to get rid of non-chr21 variants, this helps reduce maximum memory needed.

**Comment by bioinfo89** [comment]
Alright thanks Guo, I will try that!


Best,
Khyati Chandratre

**Comment by bioinfo89** [comment]
I tried to increase the heap size but I get the same error:

```
Traceback (most recent call last):
  File "/home/krc190002/scratch/WGS_tools/varsim/varsim.py", line 719, in <module>
    java=args.java)
  File "/home/krc190002/scratch/WGS_tools/varsim/varsim.py", line 333, in varsim_main
    run_randvcf(os.path.realpath(sampling_vcf), rand_vcf_out_fd, rand_vcf_log_fd, seed, sex, randvcf_options, reference, java)
  File "/home/krc190002/scratch/WGS_tools/varsim/varsim.py", line 242, in run_randvcf
    subprocess.check_call(rand_vcf_command, stdout=out_vcf_fd, stderr=log_file_fd)
  File "/opt/ohpc/pub/packages/anaconda2/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/scratch/krc190002/WGS_tools/varsim/opt/jdk1.8.0_131/bin/java', '-Xmx35g', '-jar', '/scratch/krc190002/WGS_tools/varsim/VarSim.jar', 'randvcf2vcf', '-seed', '0', '-t', 'MALE', '-num_snp', '100', '-num_ins', '50', '-num_del', '500', '-num_mnp', '0', '-num_complex', '0', '-num_dup', '0', '-num_inv', '0', '-novel', '0.01', '-min_len', '0', '-max_len', '29', '-prop_het', '0.6', '-ref', '/scratch/krc190002/WGS_SV_analysis/hg19/chr21.fa', '-vcf', '/scratch/krc190002/WGS_tools/varsim/All_20170710_chr21_variants.vcf']' returned non-zero exit status 1
```

**Comment by yunfeiguo** [comment]
Hi @bioinfo89 please provide the log for executing `randvcf2vcf` step. There should be a `RandVCF2VCF.err` log file inside your `log` folder.

**Comment by bioinfo89** [comment]
Please find attached the error file.
Best,
Khyati Chandratre

**Comment by yunfeiguo** [comment]
There is no attachment.

**Comment by bioinfo89** [comment]
[RandVCF2VCF.err.txt](https://github.com/bioinform/varsim/files/5197121/RandVCF2VCF.err.txt)

**Comment by yunfeiguo** [comment]
The last part of the log says
```08 Sep 2020 17:58:08,945 ERROR [main] (SimpleReference.java:169): Contig not found: 21
Exception in thread "main" java.lang.NullPointerException
	at com.bina.varsim.types.variant.Variant.setNovelPosition(Variant.java:295)
	at com.bina.varsim.tools.simulation.RandVCF2VCF.randOutputVcfRecord(RandVCF2VCF.java:255)
	at com.bina.varsim.tools.simulation.RandVCF2VCF.sampleFromVCF(RandVCF2VCF.java:226)
	at com.bina.varsim.tools.simulation.RandVCF2VCF.run(RandVCF2VCF.java:294)
	at com.bina.varsim.VarSim.runVarSimTool(VarSim.java:65)
	at com.bina.varsim.VarSim.run(VarSim.java:121)
	at com.bina.varsim.VarSim.main(VarSim.java:32)
```
So apparently the chromosome names in reference and VCF do not match. Make sure they either BOTH are `chr21` or BOTH are `21` (no `chr`).

**Comment by bioinfo89** [comment]
That works! Thanks!
