### ISSUE TITLE
samcompare supporting single-end reads

### ISSUE THREAD

**Issue by wx115** [bioinform/varsim#36]
Hi, I've been using VarSim to simulate reads for alignment, and would like to compare the alignment accuracy before secondary analysis. I'd like to test with single-end reads. However fastqLiftover does not support single-end, therefore I used art_illumina to generate pairend reads, and use bwa on one read file to generate .sam and .bam files. Then it seems to me that samcompare does not support single-end read. The error message is copied as below.

INFO [main] (SAMcompare.java:207): Reading file: out/sorted_reads_k19.bam
Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read
at htsjdk.samtools.SAMRecord.requireReadPaired(SAMRecord.java:654)
at htsjdk.samtools.SAMRecord.getFirstOfPairFlag(SAMRecord.java:712)
at com.bina.varsim.SAMcompare.run(SAMcompare.java:223)
at com.bina.varsim.VarSim.run(VarSim.java:61)
at com.bina.varsim.VarSim.main(VarSim.java:83)

I'd like to understand how to check alignment accuracy for single-end reads using the VarSim tools. Could you please advise? Thank you!

**Comment by marghoob** [comment]
Hi Wenxian,

Which version of VarSim are you using? The most recent version (v0.5.2)[https://github.com/bioinform/varsim/releases/tag/v0.5.2] should support single-ended reads in samcompare. Please try to run with the latest version and let us know how it goes. 

Regards,
Marghoob.
